keymap:
  - name: chrome navigation
    application:
      only: google-chrome
    remap:
      C-ALT-H: C-SHIFT-TAB
      C-ALT-L: C-TAB
      ALT-J: DOWN
      ALT-K: UP
  - name: firefox navigation
    application:
      only: firefox
    remap:
      C-ALT-H: C-SHIFT-TAB
      C-ALT-L: C-TAB
      ALT-J: DOWN
      ALT-K: UP
      ALT-H: LEFT
      ALT-L: RIGHT
